apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"         # [OPTIONAL] if not provided, will default to "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "4bb98df3-4f04-4497-add6-871275a589e8"
    # userAssignedIdentityID: "53ecbf8b-166a-4c66-a553-dde574b96f50"
    keyvaultName: "ngAkv"          # the name of the KeyVault
    cloudName: "AzurePublicCloud"          # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: "RABBITMQ-HOST-NAME"
          objectType: secret        # object types: secret, key or cert
          #objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
        - |
          objectName: "RABBITMQ-USER-NAME"
          objectType: secret
        - |
          objectName: "RABBITMQ-PASSWORD"
          objectType: secret
        - |
          objectName: "RABBITMQ-BATCH-SIZE"
          objectType: secret
    resourceGroup: "akvResourceGroup"               # [REQUIRED for version < 0.0.4] the resource group of the KeyVault
    subscriptionId: "065cf559-687c-4233-a331-564f10c8b9ed"            # [REQUIRED for version < 0.0.4] the subscription ID of the KeyVault
    tenantId: "c5ec075b-004b-43dd-9cd6-07bfd286c174"                    # the tenant ID of the KeyVault